name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint_eof_newlines:
    name: Lint EOF Newlines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check EOF Newlines
        run: bash scripts/ci_lint_eof_newlines.sh ./
  build_binary:
    name: Build Binary
    runs-on: ubuntu-latest
    needs: lint_eof_newlines
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pre-Reqs
        run: bash scripts/setup_ubuntu.sh
      - name: Build
        run: make all
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build_binary
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pre-Reqs
        run: bash scripts/setup_ubuntu.sh
      - name: Build
        run: ceedling test:all
